### ISSUE TITLE
Error: EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by 0o-de-lally** [jshimko/meteor-launchpad#10]
I'm getting this error in docker cloud automated builds, but not in quay.io builds. Quay builds perfectly. I don't know what a cross-device link is, in docker context.

The full error is:
`Error: EXDEV: cross-device link not permitted, rename '/opt/meteor/dist/bundle' -> '/opt/meteor/dist/bundle-garbage-14tplr2'`

Cross posted here:
https://github.com/docker/hub-feedback/issues/852

**Comment by Netherdrake** [comment]
+1

```
KernelVersion: 4.5.7-std-3
Os: linux
BuildTime: 2016-10-11T17:00:50.484464535+00:00
ApiVersion: 1.24
Version: 1.12.2
GitCommit: bb80604
Arch: amd64
GoVersion: go1.6.3
Starting build of index.docker.io/furion/webui:latest...
Step 1 : FROM jshimko/meteor-launchpad:latest
# Executing 4 build triggers...
Step 1 : COPY . $APP_SOURCE_DIR
Step 1 : RUN bash $BUILD_SCRIPTS_DIR/install-phantom.sh
---> Running in e56f1621cf0f
Step 1 : RUN bash $BUILD_SCRIPTS_DIR/install-mongo.sh
---> Running in 9aad455150d1
Step 1 : RUN cd $APP_SOURCE_DIR && bash $BUILD_SCRIPTS_DIR/install-meteor.sh && bash $BUILD_SCRIPTS_DIR/build-meteor.sh && bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh
---> Running in 929b5c36d6c5
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 7784 0 7784 0 0 8672 0 --:--:-- --:--:-- --:--:-- 8668
[-] Installing Meteor 1.4.1.1...
Downloading Meteor distribution
Meteor 1.4.1.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
To get started fast:
$ meteor create ~/my_cool_app
$ cd ~/my_cool_app
$ meteor
Or see the docs at:
docs.meteor.com
[-] Building Meteor application...
> bcrypt@0.8.7 install /opt/meteor/src/node_modules/bcrypt
> node-gyp rebuild
make: Entering directory '/opt/meteor/src/node_modules/bcrypt/build'
CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
COPY Release/bcrypt_lib.node
make: Leaving directory '/opt/meteor/src/node_modules/bcrypt/build'
webui@ /opt/meteor/src
+-- bcrypt@0.8.7
| +-- bindings@1.2.1
| `-- nan@2.3.5
`-- meteor-node-stubs@0.2.3
+-- assert@1.3.0
+-- browserify-zlib@0.1.4
| `-- pako@0.2.8
+-- buffer@4.5.1
| +-- base64-js@1.1.2
| +-- ieee754@1.1.6
| `-- isarray@1.0.0
+-- console-browserify@1.1.0
| `-- date-now@0.1.4
+-- constants-browserify@1.0.0
+-- crypto-browserify@3.11.0
| +-- browserify-cipher@1.0.0
| | +-- browserify-aes@1.0.6
| | | +-- buffer-xor@1.0.3
| | | `-- cipher-base@1.0.2
| | +-- browserify-des@1.0.0
| | | +-- cipher-base@1.0.2
| | | `-- des.js@1.0.0
| | | `-- minimalistic-assert@1.0.0
| | `-- evp_bytestokey@1.0.0
| +-- browserify-sign@4.0.0
| | +-- bn.js@4.11.1
| | +-- browserify-rsa@4.0.1
| | +-- elliptic@6.2.3
| | | +-- brorand@1.0.5
| | | `-- hash.js@1.0.3
| | `-- parse-asn1@5.0.0
| | +-- asn1.js@4.5.2
| | | `-- minimalistic-assert@1.0.0
| | +-- browserify-aes@1.0.6
| | | +-- buffer-xor@1.0.3
| | | `-- cipher-base@1.0.2
| | `-- evp_bytestokey@1.0.0
| +-- create-ecdh@4.0.0
| | +-- bn.js@4.11.1
| | `-- elliptic@6.2.3
| | +-- brorand@1.0.5
| | `-- hash.js@1.0.3
| +-- create-hash@1.1.2
| | +-- cipher-base@1.0.2
| | +-- ripemd160@1.0.1
| | `-- sha.js@2.4.5
| +-- create-hmac@1.1.4
| +-- diffie-hellman@5.0.2
| | +-- bn.js@4.11.1
| | `-- miller-rabin@4.0.0
| | `-- brorand@1.0.5
| +-- inherits@2.0.1
| +-- pbkdf2@3.0.4
| +-- public-encrypt@4.0.0
| | +-- bn.js@4.11.1
| | +-- browserify-rsa@4.0.1
| | `-- parse-asn1@5.0.0
| | +-- asn1.js@4.5.2
| | | `-- minimalistic-assert@1.0.0
| | +-- browserify-aes@1.0.6
| | | +-- buffer-xor@1.0.3
| | | `-- cipher-base@1.0.2
| | `-- evp_bytestokey@1.0.0
| `-- randombytes@2.0.3
+-- domain-browser@1.1.7
+-- events@1.1.0
+-- http-browserify@1.7.0
| +-- Base64@0.2.1
| `-- inherits@2.0.1
+-- https-browserify@0.0.1
+-- os-browserify@0.2.1
+-- path-browserify@0.0.0
+-- process@0.11.2
+-- punycode@1.4.1
+-- querystring-es3@0.2.1
+-- readable-stream@2.0.6
| +-- core-util-is@1.0.2
| +-- inherits@2.0.1
| +-- isarray@1.0.0
| +-- process-nextick-args@1.0.6
| `-- util-deprecate@1.0.2
+-- stream-browserify@2.0.1
| `-- inherits@2.0.1
+-- string_decoder@0.10.31
+-- timers-browserify@1.4.2
+-- tty-browserify@0.0.0
+-- url@0.11.0
| +-- punycode@1.3.2
| `-- querystring@0.2.0
+-- util@0.10.3
| `-- inherits@2.0.1
`-- vm-browserify@0.0.4
`-- indexof@0.0.1
/home/node/.meteor/packages/coffeescript/.1.0.17.1oz9l3e++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
throw error;
^
Error: EXDEV: cross-device link not permitted, rename '/opt/meteor/dist/bundle' -> '/opt/meteor/dist/bundle-garbage-x594la'
at Error (native)
at Object.fs.renameSync (fs.js:681:18)
at Object.wrapper [as rename] (/tools/fs/files.js:1519:35)
at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:959:11)
at Builder.complete (/tools/isobuild/builder.js:608:13)
at /tools/isobuild/bundler.js:2418:13
at /tools/isobuild/bundler.js:2326:7
at /tools/isobuild/bundler.js:2732:22
at /tools/utils/buildmessage.js:271:13
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:264:29
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:262:18
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:253:23
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.capture (/tools/utils/buildmessage.js:252:19)
at bundle (/tools/isobuild/bundler.js:2567:31)
at /tools/isobuild/bundler.js:2514:32
at Object.withCache (/tools/fs/files.js:1585:12)
at Object.exports.bundle (/tools/isobuild/bundler.js:2514:16)
at buildCommand (/tools/cli/commands.js:918:30)
at Command.func (/tools/cli/commands.js:798:12)
at /tools/cli/main.js:1410:23
Removing intermediate container 46b783339a77
Removing intermediate container e56f1621cf0f
Removing intermediate container 9aad455150d1
Removing intermediate container 929b5c36d6c5
The command '/bin/sh -c cd $APP_SOURCE_DIR && bash $BUILD_SCRIPTS_DIR/install-meteor.sh && bash $BUILD_SCRIPTS_DIR/build-meteor.sh && bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
ERROR: Build failed: The command '/bin/sh -c cd $APP_SOURCE_DIR && bash $BUILD_SCRIPTS_DIR/install-meteor.sh && bash $BUILD_SCRIPTS_DIR/build-meteor.sh && bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
ERROR: Build failed with exit code 2
ERROR: Build in 'master' (fe3c9fb8) failed in 0:10:33
```

**Comment by jshimko** [comment]
Please try the latest build and see if it fixes this issue for you.

``` sh
# don't forget to...

docker pull jshimko/meteor-launchpad:latest
```

**Comment by 0o-de-lally** [comment]
I think this error went away. But if you still try to build on docker-cloud's infrastructure, I get a known docker-cloud error: https://github.com/docker/hub-feedback/issues/727

Choosing: "build on my own infrastructure " solves this on docker-cloud, until they solve the problem. 

I'm guessing this can be closed, I can't reproduce it.

**Comment by jshimko** [comment]
Sounds good.  Thanks @keyscores.
