### ISSUE TITLE
PhantomJS installs erroneously

### ISSUE THREAD

**Issue by xwilders** [jshimko/meteor-launchpad#12]
Firstly thanks for your work in maintaining this image!

In the latest version (& with Meteor 1.4.2), and without any .launchpad.conf file, phantomJS nevertheless tries to install and results in the following error:

```
47 > fibers@1.0.15 install /opt/meteor/dist/bundle/programs/server/node_modules/fibers > node build.js || nodejs build.js
48`linux-x64-46` exists; testing
49Binary is fine; exiting
50 > meteor-dev-bundle@0.0.0 install /opt/meteor/dist/bundle/programs/server > node npm-rebuild.js
51 > fsevents@1.0.14 install /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents > node-pre-gyp install --fallback-to-build
52node-pre-gyp
53 ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-linux-x64.tar.gz
54node-pre-gyp
55ERR!
56Pre-built binaries not found for fsevents@1.0.14 and node@4.6.1 (node-v46 ABI) (falling back to source compile with node-gyp)
57
58make: Entering directory '/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents/build'
59 SOLINK_MODULE(target) Release/obj.target/.node
60 COPY Release/.node
61make: Leaving directory '/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents/build'
62 > sauce-connect-launcher@0.13.0 postinstall /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/sauce-connect-launcher > node scripts/install.js
63 > phantomjs-prebuilt@2.1.13 install /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt > node install.js
64PhantomJS not found on PATH
65Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
66Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
67Receiving...
68
69Received 22866K total.
70Extracting tar contents (via spawned process)
71Removing /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/phantom
72Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1477693519804/phantomjs-2.1.1-linux-x86_64 -> /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/phantom
73Writing location.js file
74Phantom installation failed { [Error: EACCES: permission denied, open '/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js'] errno: -13, code: 'EACCES', syscall: 'open', path: '/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js' } Error: EACCES: permission denied, open '/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js' at Error (native) at Object.fs.openSync (fs.js:549:18) at Object.fs.writeFileSync (fs.js:1156:15) at writeLocationFile (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/util.js:84:6) at Promise._successFn (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/install.js:88:5) at nextTickCallback (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/kew/kew.js:47:28) at nextTickCallbackWith0Args (node.js:420:9) at process._tickCallback (node.js:349:13)
```

**Comment by xwilders** [comment]
Nvm it's a bug with meteor 1.4.2 & moment's atmosphere package: https://github.com/moment/moment/issues/3531
