### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by heysailor** [jshimko/meteor-launchpad#51]
Building on docker cloud with your docker-compose.yml produces the following error, using Meteor 1.5.1:

```
> meteor-dev-bundle@0.0.0 install /opt/meteor/dist/bundle/programs/server
> node npm-rebuild.js
> bcrypt@1.0.2 install /opt/meteor/dist/bundle/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
module.js:327
throw err;
^
Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
```

**Comment by jshimko** [comment]
`meteor npm uninstall -S bcrypt`

https://github.com/reactioncommerce/reaction/issues/2333#issuecomment-315956762

**Comment by heysailor** [comment]
Ah, thank you.

**Comment by jshimko** [comment]
It's obviously not the ideal fix, but it's outside of this project and it fixes the problem, so it's the current best answer.

**Comment by jshimko** [comment]
The error is also macOS-only, so you don't need to remove that package if you do your builds on any other OS.
