### ISSUE TITLE
NPM module babel-runtime not installing on build

### ISSUE THREAD

**Issue by apdjustino** [jshimko/meteor-launchpad#77]
Hi, I have used meteor-launchpad previously and it has worked great for me. I just tried building an image using meteor-launchpad that I had previously been using mup for deployment, and am having trouble getting to run. The image builds without errors, but when running docker run I get the following error (using docker logs):

=> Starting app on port 3000...
/opt/meteor/dist/bundle/programs/server/boot.js:348
}).run();
   ^

Error: The babel-runtime npm package could not be found in your node_modules
directory. Please run the following command to install it:

  meteor npm install --save babel-runtime

    at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at require (packages/modules-runtime.js:106:16)
    at packages/babel-runtime.js:139:15
    at packages/babel-runtime.js:150:3
    at /opt/meteor/dist/bundle/programs/server/boot.js:295:34
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/dist/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/dist/bundle/programs/server/boot.js:128:5
    at /opt/meteor/dist/bundle/programs/server/boot.js:344:5

This is confusing, because in the build it looks like npm modules are successfully installing the npm install command. Here is the relevant output for the build:

[-] Running npm install in app directory...

> bcrypt@1.0.3 install /opt/meteor/src/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/opt/meteor/src/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
urbansimdataexplorer@1.0.0 /opt/meteor/src
+-- babel-runtime@6.26.0 
| +-- core-js@2.5.1 
| `-- regenerator-runtime@0.11.0 
+-- bcrypt@1.0.3 
| +-- nan@2.6.2 
| `-- node-pre-gyp@0.6.36 
|   +-- mkdirp@0.5.1 
|   | `-- minimist@0.0.8 
|   +-- nopt@4.0.1 
|   | +-- abbrev@1.1.1 
|   | `-- osenv@0.1.4 
|   |   +-- os-homedir@1.0.2 
|   |   `-- os-tmpdir@1.0.2 
|   +-- npmlog@4.1.2 
|   | +-- are-we-there-yet@1.1.4 
|   | | `-- delegates@1.0.0 
|   | +-- console-control-strings@1.1.0 
|   | +-- gauge@2.7.4 
|   | | +-- aproba@1.2.0 
|   | | +-- has-unicode@2.0.1 
|   | | +-- object-assign@4.1.1 
|   | | +-- signal-exit@3.0.2 
|   | | +-- string-width@1.0.2 
|   | | | +-- code-point-at@1.1.0 
|   | | | `-- is-fullwidth-code-point@1.0.0 
|   | | |   `-- number-is-nan@1.0.1 
|   | | +-- strip-ansi@3.0.1 
|   | | | `-- ansi-regex@2.1.1 
|   | | `-- wide-align@1.1.2 
|   | `-- set-blocking@2.0.0 
|   +-- rc@1.2.2 
|   | +-- deep-extend@0.4.2 
|   | +-- ini@1.3.4 
|   | +-- minimist@1.2.0 
|   | `-- strip-json-comments@2.0.1 
|   +-- request@2.83.0 
|   | +-- aws-sign2@0.7.0 
|   | +-- aws4@1.6.0 
|   | +-- caseless@0.12.0 
|   | +-- combined-stream@1.0.5 
|   | | `-- delayed-stream@1.0.0 
|   | +-- extend@3.0.1 
|   | +-- forever-agent@0.6.1 
|   | +-- form-data@2.3.1 
|   | | `-- asynckit@0.4.0 
|   | +-- har-validator@5.0.3 
|   | | +-- ajv@5.3.0 
|   | | | +-- co@4.6.0 
|   | | | +-- fast-deep-equal@1.0.0 
|   | | | +-- fast-json-stable-stringify@2.0.0 
|   | | | `-- json-schema-traverse@0.3.1 
|   | | `-- har-schema@2.0.0 
|   | +-- hawk@6.0.2 
|   | | +-- boom@4.3.1 
|   | | +-- cryptiles@3.1.2 
|   | | | `-- boom@5.2.0 
|   | | +-- hoek@4.2.0 
|   | | `-- sntp@2.1.0 
|   | +-- http-signature@1.2.0 
|   | | +-- assert-plus@1.0.0 
|   | | +-- jsprim@1.4.1 
|   | | | +-- extsprintf@1.3.0 
|   | | | +-- json-schema@0.2.3 
|   | | | `-- verror@1.10.0 
|   | | `-- sshpk@1.13.1 
|   | |   +-- asn1@0.2.3 
|   | |   +-- bcrypt-pbkdf@1.0.1 
|   | |   +-- dashdash@1.14.1 
|   | |   +-- ecc-jsbn@0.1.1 
|   | |   +-- getpass@0.1.7 
|   | |   +-- jsbn@0.1.1 
|   | |   `-- tweetnacl@0.14.5 
|   | +-- is-typedarray@1.0.0 
|   | +-- isstream@0.1.2 
|   | +-- json-stringify-safe@5.0.1 
|   | +-- mime-types@2.1.17 
|   | | `-- mime-db@1.30.0 
|   | +-- oauth-sign@0.8.2 
|   | +-- performance-now@2.1.0 
|   | +-- qs@6.5.1 
|   | +-- safe-buffer@5.1.1 
|   | +-- stringstream@0.0.5 
|   | +-- tough-cookie@2.3.3 
|   | | `-- punycode@1.4.1 
|   | +-- tunnel-agent@0.6.0 
|   | `-- uuid@3.1.0 
|   +-- rimraf@2.6.2 
|   | `-- glob@7.1.2 
|   |   +-- fs.realpath@1.0.0 
|   |   +-- inflight@1.0.6 
|   |   +-- minimatch@3.0.4 
|   |   | `-- brace-expansion@1.1.8 
|   |   |   +-- balanced-match@1.0.0 
|   |   |   `-- concat-map@0.0.1 
|   |   `-- path-is-absolute@1.0.1 
|   +-- semver@5.4.1 
|   +-- tar@2.2.1 
|   | +-- block-stream@0.0.9 
|   | +-- fstream@1.0.11 
|   | | `-- graceful-fs@4.1.11 
|   | `-- inherits@2.0.3 
|   `-- tar-pack@3.4.1 
|     +-- debug@2.6.9 
|     | `-- ms@2.0.0 
|     +-- fstream-ignore@1.0.5 
|     +-- once@1.4.0 
|     | `-- wrappy@1.0.2 
|     +-- readable-stream@2.3.3 
|     | +-- core-util-is@1.0.2 
|     | +-- isarray@1.0.0 
|     | +-- process-nextick-args@1.0.7 
|     | +-- string_decoder@1.0.3 
|     | `-- util-deprecate@1.0.2 
|     `-- uid-number@0.0.6 
`-- topojson@1.6.27 
  +-- d3@3.5.17 
  +-- d3-geo-projection@0.2.16 
  | `-- brfs@1.4.3 
  |   +-- quote-stream@1.0.2 
  |   | +-- buffer-equal@0.0.1 
  |   | `-- minimist@1.2.0 
  |   +-- resolve@1.5.0 
  |   | `-- path-parse@1.0.5 
  |   +-- static-module@1.5.0 
  |   | +-- concat-stream@1.6.0 
  |   | | `-- typedarray@0.0.6 
  |   | +-- duplexer2@0.0.2 
  |   | | `-- readable-stream@1.1.14 
  |   | |   +-- isarray@0.0.1 
  |   | |   `-- string_decoder@0.10.31 
  |   | +-- escodegen@1.3.3 
  |   | | +-- esprima@1.1.1 
  |   | | +-- estraverse@1.5.1 
  |   | | +-- esutils@1.0.0 
  |   | | `-- source-map@0.1.43 
  |   | |   `-- amdefine@1.0.1 
  |   | +-- falafel@2.1.0 
  |   | | +-- acorn@5.2.1 
  |   | | +-- foreach@2.0.5 
  |   | | +-- isarray@0.0.1 
  |   | | `-- object-keys@1.0.11 
  |   | +-- has@1.0.1 
  |   | | `-- function-bind@1.1.1 
  |   | +-- object-inspect@0.4.0 
  |   | +-- quote-stream@0.0.0 
  |   | +-- readable-stream@1.0.34 
  |   | | +-- isarray@0.0.1 
  |   | | `-- string_decoder@0.10.31 
  |   | +-- shallow-copy@0.0.1 
  |   | +-- static-eval@0.2.4 
  |   | | `-- escodegen@0.0.28 
  |   | |   +-- esprima@1.0.4 
  |   | |   `-- estraverse@1.3.2 
  |   | `-- through2@0.4.2 
  |   |   `-- xtend@2.1.2 
  |   |     `-- object-keys@0.4.0 
  |   `-- through2@2.0.3 
  |     `-- xtend@4.0.1 
  +-- d3-queue@2.0.3 
  +-- optimist@0.3.7 
  | `-- wordwrap@0.0.3 
  +-- rw@1.3.3 
  `-- shapefile@0.3.1 
    +-- d3-queue@1.2.3 
    `-- iconv-lite@0.2.11 

[-] Building Meteor application...

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

[-] Running npm install in the server bundle...

> fibers@1.0.15 install /opt/meteor/dist/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /opt/meteor/dist/bundle/programs/server
> node npm-rebuild.js

> bcrypt@1.0.3 install /opt/meteor/dist/bundle/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/opt/meteor/dist/bundle/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
abbrev@1.1.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/abbrev
acorn@5.2.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/acorn
ajv@5.3.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/ajv
co@4.6.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/co
fast-deep-equal@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/fast-deep-equal
fast-json-stable-stringify@2.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/fast-json-stable-stringify
json-schema-traverse@0.3.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/json-schema-traverse
amdefine@1.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/amdefine
ansi-regex@2.1.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/ansi-regex
aproba@1.2.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/aproba
are-we-there-yet@1.1.4 /opt/meteor/dist/bundle/programs/server/npm/node_modules/are-we-there-yet
delegates@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/delegates
readable-stream@2.3.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/readable-stream
core-util-is@1.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/core-util-is
inherits@2.0.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/inherits
isarray@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/isarray
process-nextick-args@1.0.7 /opt/meteor/dist/bundle/programs/server/npm/node_modules/process-nextick-args
safe-buffer@5.1.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/safe-buffer
string_decoder@1.0.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/string_decoder
util-deprecate@1.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/util-deprecate
asn1@0.2.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/asn1
assert-plus@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/assert-plus
asynckit@0.4.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/asynckit
aws-sign2@0.7.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/aws-sign2
aws4@1.6.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/aws4
babel-runtime@6.26.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/babel-runtime
core-js@2.5.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/core-js
regenerator-runtime@0.11.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/regenerator-runtime
balanced-match@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/balanced-match
bcrypt@1.0.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/bcrypt
nan@2.6.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/nan
node-pre-gyp@0.6.36 /opt/meteor/dist/bundle/programs/server/npm/node_modules/node-pre-gyp
mkdirp@0.5.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/mkdirp
minimist@0.0.8 /opt/meteor/dist/bundle/programs/server/npm/node_modules/minimist
nopt@4.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/nopt
osenv@0.1.4 /opt/meteor/dist/bundle/programs/server/npm/node_modules/osenv
os-homedir@1.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/os-homedir
os-tmpdir@1.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/os-tmpdir
npmlog@4.1.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/npmlog
console-control-strings@1.1.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/console-control-strings
gauge@2.7.4 /opt/meteor/dist/bundle/programs/server/npm/node_modules/gauge
has-unicode@2.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/has-unicode
object-assign@4.1.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/object-assign
signal-exit@3.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/signal-exit
string-width@1.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/string-width
code-point-at@1.1.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/code-point-at
is-fullwidth-code-point@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/is-fullwidth-code-point
number-is-nan@1.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/number-is-nan
strip-ansi@3.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/strip-ansi
wide-align@1.1.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/wide-align
set-blocking@2.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/set-blocking
rc@1.2.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/rc
deep-extend@0.4.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/deep-extend
ini@1.3.4 /opt/meteor/dist/bundle/programs/server/npm/node_modules/ini
minimist@1.2.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/rc/node_modules/minimist
strip-json-comments@2.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/strip-json-comments
request@2.83.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/request
caseless@0.12.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/caseless
combined-stream@1.0.5 /opt/meteor/dist/bundle/programs/server/npm/node_modules/combined-stream
delayed-stream@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/delayed-stream
extend@3.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/extend
forever-agent@0.6.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/forever-agent
form-data@2.3.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/form-data
mime-types@2.1.17 /opt/meteor/dist/bundle/programs/server/npm/node_modules/mime-types
mime-db@1.30.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/mime-db
har-validator@5.0.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/har-validator
har-schema@2.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/har-schema
hawk@6.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/hawk
boom@4.3.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/boom
hoek@4.2.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/hoek
cryptiles@3.1.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/cryptiles
boom@5.2.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/cryptiles/node_modules/boom
sntp@2.1.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/sntp
http-signature@1.2.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/http-signature
jsprim@1.4.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/jsprim
extsprintf@1.3.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/extsprintf
json-schema@0.2.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/json-schema
verror@1.10.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/verror
sshpk@1.13.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/sshpk
dashdash@1.14.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/dashdash
getpass@0.1.7 /opt/meteor/dist/bundle/programs/server/npm/node_modules/getpass
is-typedarray@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/is-typedarray
isstream@0.1.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/isstream
json-stringify-safe@5.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/json-stringify-safe
oauth-sign@0.8.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/oauth-sign
performance-now@2.1.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/performance-now
qs@6.5.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/qs
stringstream@0.0.5 /opt/meteor/dist/bundle/programs/server/npm/node_modules/stringstream
tough-cookie@2.3.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/tough-cookie
punycode@1.4.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/punycode
tunnel-agent@0.6.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/tunnel-agent
uuid@3.1.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/uuid
rimraf@2.6.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/rimraf
glob@7.1.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/glob
fs.realpath@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/fs.realpath
inflight@1.0.6 /opt/meteor/dist/bundle/programs/server/npm/node_modules/inflight
once@1.4.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/once
wrappy@1.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/wrappy
minimatch@3.0.4 /opt/meteor/dist/bundle/programs/server/npm/node_modules/minimatch
brace-expansion@1.1.8 /opt/meteor/dist/bundle/programs/server/npm/node_modules/brace-expansion
concat-map@0.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/concat-map
path-is-absolute@1.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/path-is-absolute
semver@5.4.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/semver
tar@2.2.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/tar
block-stream@0.0.9 /opt/meteor/dist/bundle/programs/server/npm/node_modules/block-stream
fstream@1.0.11 /opt/meteor/dist/bundle/programs/server/npm/node_modules/fstream
graceful-fs@4.1.11 /opt/meteor/dist/bundle/programs/server/npm/node_modules/graceful-fs
tar-pack@3.4.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/tar-pack
debug@2.6.9 /opt/meteor/dist/bundle/programs/server/npm/node_modules/debug
ms@2.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/ms
fstream-ignore@1.0.5 /opt/meteor/dist/bundle/programs/server/npm/node_modules/fstream-ignore
uid-number@0.0.6 /opt/meteor/dist/bundle/programs/server/npm/node_modules/uid-number
bcrypt-pbkdf@1.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/bcrypt-pbkdf
tweetnacl@0.14.5 /opt/meteor/dist/bundle/programs/server/npm/node_modules/tweetnacl
brfs@1.4.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/brfs
quote-stream@1.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/quote-stream
buffer-equal@0.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/buffer-equal
minimist@1.2.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/quote-stream/node_modules/minimist
through2@2.0.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/through2
xtend@4.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/xtend
resolve@1.5.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/resolve
path-parse@1.0.5 /opt/meteor/dist/bundle/programs/server/npm/node_modules/path-parse
static-module@1.5.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-module
concat-stream@1.6.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/concat-stream
typedarray@0.0.6 /opt/meteor/dist/bundle/programs/server/npm/node_modules/typedarray
duplexer2@0.0.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/duplexer2
readable-stream@1.1.14 /opt/meteor/dist/bundle/programs/server/npm/node_modules/duplexer2/node_modules/readable-stream
isarray@0.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/duplexer2/node_modules/isarray
string_decoder@0.10.31 /opt/meteor/dist/bundle/programs/server/npm/node_modules/duplexer2/node_modules/string_decoder
escodegen@1.3.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/escodegen
esprima@1.1.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/esprima
estraverse@1.5.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/estraverse
esutils@1.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/esutils
falafel@2.1.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/falafel
foreach@2.0.5 /opt/meteor/dist/bundle/programs/server/npm/node_modules/foreach
isarray@0.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/falafel/node_modules/isarray
object-keys@1.0.11 /opt/meteor/dist/bundle/programs/server/npm/node_modules/object-keys
has@1.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/has
function-bind@1.1.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/function-bind
object-inspect@0.4.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/object-inspect
quote-stream@0.0.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-module/node_modules/quote-stream
through2@0.4.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-module/node_modules/through2
readable-stream@1.0.34 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-module/node_modules/readable-stream
isarray@0.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-module/node_modules/isarray
string_decoder@0.10.31 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-module/node_modules/string_decoder
xtend@2.1.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-module/node_modules/xtend
object-keys@0.4.0 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-module/node_modules/object-keys
shallow-copy@0.0.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/shallow-copy
static-eval@0.2.4 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-eval
escodegen@0.0.28 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-eval/node_modules/escodegen
esprima@1.0.4 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-eval/node_modules/esprima
estraverse@1.3.2 /opt/meteor/dist/bundle/programs/server/npm/node_modules/static-eval/node_modules/estraverse
d3@3.5.17 /opt/meteor/dist/bundle/programs/server/npm/node_modules/d3
d3-geo-projection@0.2.16 /opt/meteor/dist/bundle/programs/server/npm/node_modules/d3-geo-projection
d3-queue@2.0.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/d3-queue
ecc-jsbn@0.1.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/ecc-jsbn
jsbn@0.1.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/jsbn
iconv-lite@0.2.11 /opt/meteor/dist/bundle/programs/server/npm/node_modules/iconv-lite
optimist@0.3.7 /opt/meteor/dist/bundle/programs/server/npm/node_modules/optimist
wordwrap@0.0.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/wordwrap
rw@1.3.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/rw
shapefile@0.3.1 /opt/meteor/dist/bundle/programs/server/npm/node_modules/shapefile
d3-queue@1.2.3 /opt/meteor/dist/bundle/programs/server/npm/node_modules/shapefile/node_modules/d3-queue
source-map@0.1.43 /opt/meteor/dist/bundle/programs/server/npm/node_modules/source-map
topojson@1.6.27 /opt/meteor/dist/bundle/programs/server/npm/node_modules/topojson
{
  "meteor-dev-bundle": "0.0.0",
  "npm": "3.10.9",
  "ares": "1.10.1-DEV",
  "http_parser": "2.7.0",
  "icu": "56.1",
  "modules": "46",
  "node": "4.6.2",
  "openssl": "1.0.2j",
  "uv": "1.9.1",
  "v8": "4.5.103.42",
  "zlib": "1.2.8"
}
meteor-dev-bundle@0.0.0 /opt/meteor/dist/bundle/programs/server
+-- amdefine@1.0.1 
+-- asap@2.0.5 
+-- fibers@1.0.15 
+-- meteor-promise@0.8.0 
+-- node-gyp@3.4.0 
| +-- fstream@1.0.11 
| | `-- inherits@2.0.3 
| +-- glob@7.1.2 
| | +-- fs.realpath@1.0.0 
| | +-- inflight@1.0.6 
| | | `-- wrappy@1.0.2 
| | +-- once@1.4.0 
| | `-- path-is-absolute@1.0.1 
| +-- graceful-fs@4.1.11 
| +-- minimatch@3.0.4 
| | `-- brace-expansion@1.1.8 
| |   +-- balanced-match@1.0.0 
| |   `-- concat-map@0.0.1 
| +-- mkdirp@0.5.1 
| | `-- minimist@0.0.8 
| +-- nopt@3.0.6 
| | `-- abbrev@1.1.1 
| +-- npmlog@3.1.2 
| | +-- are-we-there-yet@1.1.4 
| | | +-- delegates@1.0.0 
| | | `-- readable-stream@2.3.3 
| | |   `-- string_decoder@1.0.3 
| | +-- console-control-strings@1.1.0 
| | +-- gauge@2.6.0 
| | | +-- aproba@1.2.0 
| | | +-- has-color@0.1.7 
| | | +-- has-unicode@2.0.1 
| | | +-- object-assign@4.1.1 
| | | +-- signal-exit@3.0.2 
| | | +-- string-width@1.0.2 
| | | | +-- code-point-at@1.1.0 
| | | | `-- is-fullwidth-code-point@1.0.0 
| | | |   `-- number-is-nan@1.0.1 
| | | +-- strip-ansi@3.0.1 
| | | | `-- ansi-regex@2.1.1 
| | | `-- wide-align@1.1.2 
| | `-- set-blocking@2.0.0 
| +-- osenv@0.1.4 
| | +-- os-homedir@1.0.2 
| | `-- os-tmpdir@1.0.2 
| +-- path-array@1.0.1 
| | `-- array-index@1.0.0 
| |   +-- debug@2.6.9 
| |   | `-- ms@2.0.0 
| |   `-- es6-symbol@3.1.1 
| |     +-- d@1.0.0 
| |     `-- es5-ext@0.10.35 
| |       `-- es6-iterator@2.0.3 
| +-- request@2.83.0 
| | +-- aws-sign2@0.7.0 
| | +-- aws4@1.6.0 
| | +-- caseless@0.12.0 
| | +-- combined-stream@1.0.5 
| | | `-- delayed-stream@1.0.0 
| | +-- extend@3.0.1 
| | +-- forever-agent@0.6.1 
| | +-- form-data@2.3.1 
| | | `-- asynckit@0.4.0 
| | +-- har-validator@5.0.3 
| | | +-- ajv@5.3.0 
| | | | +-- co@4.6.0 
| | | | +-- fast-deep-equal@1.0.0 
| | | | +-- fast-json-stable-stringify@2.0.0 
| | | | `-- json-schema-traverse@0.3.1 
| | | `-- har-schema@2.0.0 
| | +-- hawk@6.0.2 
| | | +-- boom@4.3.1 
| | | +-- cryptiles@3.1.2 
| | | | `-- boom@5.2.0 
| | | +-- hoek@4.2.0 
| | | `-- sntp@2.1.0 
| | +-- http-signature@1.2.0 
| | | +-- assert-plus@1.0.0 
| | | +-- jsprim@1.4.1 
| | | | +-- extsprintf@1.3.0 
| | | | +-- json-schema@0.2.3 
| | | | `-- verror@1.10.0 
| | | `-- sshpk@1.13.1 
| | |   +-- asn1@0.2.3 
| | |   +-- bcrypt-pbkdf@1.0.1 
| | |   +-- dashdash@1.14.1 
| | |   +-- ecc-jsbn@0.1.1 
| | |   +-- getpass@0.1.7 
| | |   +-- jsbn@0.1.1 
| | |   `-- tweetnacl@0.14.5 
| | +-- is-typedarray@1.0.0 
| | +-- isstream@0.1.2 
| | +-- json-stringify-safe@5.0.1 
| | +-- mime-types@2.1.17 
| | | `-- mime-db@1.30.0 
| | +-- oauth-sign@0.8.2 
| | +-- performance-now@2.1.0 
| | +-- qs@6.5.1 
| | +-- safe-buffer@5.1.1 
| | +-- stringstream@0.0.5 
| | +-- tough-cookie@2.3.3 
| | | `-- punycode@1.4.1 
| | +-- tunnel-agent@0.6.0 
| | `-- uuid@3.1.0 
| +-- rimraf@2.6.2 
| +-- tar@2.2.1 
| | `-- block-stream@0.0.9 
| `-- which@1.3.0 
|   `-- isexe@2.0.0 
+-- node-pre-gyp@0.6.29 
| +-- rc@1.1.7 
| | +-- deep-extend@0.4.2 
| | +-- ini@1.3.4 
| | +-- minimist@1.2.0 
| | `-- strip-json-comments@2.0.1 
| +-- rimraf@2.5.4 
| +-- semver@5.2.0 
| `-- tar-pack@3.1.4 
|   +-- debug@2.2.0 
|   | `-- ms@0.7.1 
|   +-- fstream-ignore@1.0.5 
|   +-- once@1.3.3 
|   +-- readable-stream@2.1.5 
|   | +-- buffer-shims@1.0.0 
|   | +-- core-util-is@1.0.2 
|   | +-- isarray@1.0.0 
|   | +-- process-nextick-args@1.0.7 
|   | +-- string_decoder@0.10.31 
|   | `-- util-deprecate@1.0.2 
|   +-- rimraf@2.5.4 
|   `-- uid-number@0.0.6 
+-- promise@7.1.1 
+-- semver@4.1.0 
+-- source-map@0.1.32 
+-- source-map-support@0.3.2 
`-- underscore@1.5.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

**Comment by apdjustino** [comment]
Fixed this by removing node_modules from .dockerignore
