### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by adamgins** [jshimko/meteor-launchpad#79]
Thanks for Launchpad.

Any ideas why I'd be getting this error pls:

Seems to be realted to https://atmospherejs.com/lookback/emails

```
buzzy-buzz:resources-core: updating npm dependencies -- aws-sdk,
s3-write-stream, webshot, vimeo-api, html-truncate...
node.js:489
        callback();
        ^

Error: EINVAL: invalid argument, readlink '/root/.meteor/packages/lookback_emails/.0.7.7.tbh8qe++os+web.browser+web.cordova/npm/node_modules/.bin/esvalidate'
    at Error (native)
    at Object.fs.readlinkSync (fs.js:857:18)
    at Object.realpathSync (fs.js:1457:25)
    at Object.wrapper [as realpath] (/tools/fs/files.js:1594:35)
    at getExternalPath (/tools/isobuild/builder.js:482:30)
    at /tools/isobuild/builder.js:511:32
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:464:34)
    at /tools/isobuild/builder.js:556:11
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:464:34)
    at Builder.copyDirectory (/tools/isobuild/builder.js:594:5)
    at /tools/isobuild/bundler.js:2253:17
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:2212:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2481:13)
    at /tools/isobuild/bundler.js:2600:30
    at /tools/isobuild/bundler.js:2735:9
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2725:26
    at /tools/isobuild/bundler.js:3066:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2899:31)
    at /tools/isobuild/bundler.js:2846:32
    at Object.withCache (/tools/fs/files.js:1694:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2846:16)
    at buildCommand (/tools/cli/commands.js:956:30)
    at Command.func (/tools/cli/commands.js:831:12)
    at /tools/cli/main.js:1483:23
The command '/bin/sh -c cd $APP_SOURCE_DIR &&   $BUILD_SCRIPTS_DIR/install-deps.sh &&   $BUILD_SCRIPTS_DIR/install-node.sh &&   $BUILD_SCRIPTS_DIR/install-phantom.sh &&   $BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&   $BUILD_SCRIPTS_DIR/install-mongo.sh &&   $BUILD_SCRIPTS_DIR/install-meteor.sh &&   $BUILD_SCRIPTS_DIR/build-meteor.sh &&   $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
```
Build command `docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048"  -t buzzybuzz/buzzy-main .`

Launchpad.conf 

```
# launchpad.conf

# Use apt-get to install any additional dependencies
# that you need before your building/running your app
# (default: undefined)
APT_GET_INSTALL="curl git wget"

## Install a custom Node version (default: latest 8.x)
#NODE_VERSION=8.9.0

# Installs the latest version of each (default: all false)
#INSTALL_MONGO=true
INSTALL_PHANTOMJS=true
INSTALL_GRAPHICSMAGICK=true

```

Also I am currently on Meteor 1.5.2 and using `FROM jshimko/meteor-launchpad:latest`

**Comment by adamgins** [comment]
Update I changed the `.dockerignore` to

```
.git
.meteor/local
node_modules
```
and now I am getting https://github.com/jshimko/meteor-launchpad/issues/80 not sure if this issue is further along or behind.

**Comment by jshimko** [comment]
> _Also I am currently on Meteor 1.5.2 and using FROM jshimko/meteor-launchpad:latest_

That's definitely going to be an issue if you're not overriding the NODE_VERSION.  Meteor 1.5.2 definitely doesn't support Node 8.  If you're not going to update Meteor, I don't recommend using the `latest` tag here because it's always intended to support the latest official release of Meteor.

This base image is already smart enough to install the version of Meteor that your app uses, but the Node version gets bumped every time Meteor pushes another release with a Node version change.  To override the version...

```sh
docker build \
  --build-arg NODE_VERSION="4.8.4" \
  --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" \
  -t buzzybuzz/buzzy-main .
```
