### ISSUE TITLE
Error loading after Meteor 1.6 update

### ISSUE THREAD

**Issue by aviadbd** [jshimko/meteor-launchpad#82]
After the Meteor 1.6 update, I'm still using the jshimko/meteor-launchpad:latest with the default NODE_VERSION selected (i.e. that line is commented out). I tried to force it to 8.8.1, the local meteor version I have, to no avail. The error I'm seeing when trying to start the app is:

```
=> Starting app on port 3000...
/opt/meteor/dist/bundle/programs/server/boot.js:50
    const { pause } = require("./debug.js");
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/meteor/dist/bundle/main.js:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Any ideas?

**Comment by jshimko** [comment]
You're probably using a cached copy of `jshimko/meteor-launchpad:latest`.  Docker doesn't download it again if you already have an image matching that "latest" tag locally.  So yeah, "latest" doesn't truly mean latest.

```
docker pull jshimko/meteor-launchpad:latest

docker build ...
```

I'm seriously considering removing the `:latest` tag because this isn't an uncommon point of confusion.  Many blog posts have been written on the topic.

https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

**Comment by jshimko** [comment]
And I recommend just pinning it to the tag that works with your current version of Meteor.  For example, for Meteor 1.6 it's `jshimko/meteor-launchpad:v2.3.0`.  Then next time you update Meteor, come back here and check for the current release version that supports it. I always try to get them out as fast as possible when Meteor releases a new version.  You can check the release [HISTORY.md](https://github.com/jshimko/meteor-launchpad/blob/master/HISTORY.md) for the release notes.

**Comment by aviadbd** [comment]
Did that, seemed to fix That issue but started raising new issues with my site not working. First said that core-js wasn't installed, now that it can't find the mongo-object module. I'm kind of sure it's not due to this package but due to some Meteor migration issues, am I right?

**Comment by jshimko** [comment]
Yeah, Meteor 1.6 appears to now require `core-js` to be installed.

```sh
meteor npm i -S core-js
```

**Comment by aviadbd** [comment]
Yeah.... Weird, as it worked locally without it. Also, just for documentation's sake, it seemed I had to install mongo-object the same way as well, but probably because of the autoform module.
