### ISSUE TITLE
Issue with Mongo DB

### ISSUE THREAD

**Issue by koernigo** [jshimko/meteor-launchpad#93]
Hi, I was able to run the default Meteor app in Docker with no problem.
I tried the same with the todos app and I get the following error when starting the container:

[root@localhost test8-okoernig]# docker run -e ROOT_URL=http://example.com   -e MONGO_URL=mongodb://url   -e MONGO_OPLOG_URL=mongodb://oplog_url   -e MAIL_URL=smtp://mail_url.com   -p 80:3000  okoernig/todos
=> Starting app on port 3000...

/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [url:27017] on first connect [MongoError: getaddrinfo ENOTFOUND url url:27017]
    at Pool.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)

Same thing happens with  another app I built. Any ideas what's going on?

using meteor 1.6.1 and

**Comment by jshimko** [comment]
You have to actually _set_ the `MONGO_URL`.   The example you copied from the readme (`mongodb://url`) is not a valid url.  It was just a placeholder to demonstrate the command.

**Comment by koernigo** [comment]
Thank you so much for your help.  I guess the sample app worked because it doesn't use Mongo.
Thanks again.
